### ISSUE TITLE
chore: cancel running CI jobs if a new commit is pushed

### ISSUE THREAD

**Issue by jamesmunns** [hawkw/mycelium#534]
We could apply something like this to cancel long running jobs like miri tests if we push multiple commits in succession:

https://www.meziantou.net/how-to-cancel-github-workflows-when-pushing-new-commits-on-a-branch.htm

```yml
concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
```
